version: '3'
services: 
    web:
        container_name: cakephp-web
        build: 
            context: .
            dockerfile: ./Docker/php/Dockerfile
        volumes:
            - .:/var/www/html:cached
        ports:
            - "5000:80"