version: '3'
services: 
    web:
        container_name: cakephp-web
        build: 
            context: .
            dockerfile: ./Docker/php/Dockerfile
        volumes:
            - .:/var/www/html:cached
        command: bash -c "sh docker-init-setup.sh && apache2-foreground"
        environment: 
            - APP_DEFAULT_LOCALE=ja_JP
            - APP_DEFAULT_TIMEZONE=Asia/Tokyo
        ports:
            - "5000:80"